name: MessageQuery
type: aggregate
value: count
resultType: grouped
sql: 'SELECT * from MESSAGE where id = ? '
queryParams: [
  {
    value: 1000,
    position: 1,
    type: "integer"
  },
  {

  }
]
